routes/web.php
    Route::get('/change-password', 'ProfileController@changePassword');
    Route::post('/update-password', 'ProfileController@updatePassword');
    Route::post('/update-user-info/{id}', 'ProfileController@update');
    // order history
    Route::get('/fitreatsOrderDetails', 'OrderController@displayFitreatsDetail');
    Route::get('/fitreatsOrderDetails/{id}', 'OrderController@displayFitreatUserOrders');




    // Route::get('/cancel', 'PaymentController@cancel');
    Route::get('/exportCSV', 'ProfileController@exportCSV');
});



/* Additional Work */
Route::get('/fitreats-and-supplements', 'FacilityController@fitreatsAndSupplements');
Route::post('/cart/{id}', 'CartController@store');
Route::get('/cart', 'CartController@index');
Route::get('/cart/delete/{rowId}/{id}', 'CartController@destroy');
Route::post('/cart/update/{rowId}/{id}', 'CartController@update');
Route::post('/clearCart', 'CartController@clearCart');
Route::get('/checkout', 'CheckoutController@index')->middleware('auth');
Route::post('/paypal-checkout-fitreats', 'FitreatsPayment@payWithPaypal');
Route::get('/paypal-checkout-status-fitreats', 'FitreatsPayment@getPaymentStatus')->name('statusFitreats');


// new routes for food begins here

Route::get('/', 'MainController@index');



Route::get('/contact', 'ContactController@index');
Route::post('/contact-store', 'ContactController@storing');

Route::post('/enrol-now/store', 'MainController@enrolnowstore');
Route::get('/user-register', 'ProfileController@userregister');
Route::post('/user-register', 'ProfileController@userregisterstore');
Route::post('/user-register-checkout', 'ProfileController@userRegisterCheckout');


Route::get('/about_us', 'HomeController@aboutRedirect');
Route::get('/about-us', 'HomeController@about');
// Route::get('/affiliates','HomeController@affiliates');
Route::get('/courses', 'HomeController@courses');
Route::get('/fee', 'HomeController@fee');
Route::get('/testimonial', 'HomeController@testinomial');
Route::post('/proceed-payment', 'FeeController@proceedpayment');


Route::group(['middleware' => 'auth'], function () {

    Route::get('/redirect_to_register_for_auth', 'ProductController@redirectToRegister');

    Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');
    // list all lfm routes here...
});

Route::get('/checkout/{id}', 'MainController@checkout');
Route::get('/fetch', function () {
    return view('checkout.fetch');
});
Route::get('/checkoutstore', 'MainController@checkoutindex');
Route::get('/verify', 'MainController@checkoutupdate');
Route::get('/invoice', 'FeeController@invoice');

Route::get('/invoice', 'FeeController@invoice');

Route::get('/shop', [
    'uses' => 'ProductController@getproductindex',
    'as' => 'products.index'
]);
Route::get('/create-product-categories', [
    'uses' => 'ProductcategoryController@index',
    'as' => 'productcategory.index'
]);

Route::post('/store-product-categories', [
    'uses' => 'ProductcategoryController@store',
    'as' => 'productcategory.store'
]);
Route::get('/product-category/{id}/edit', [
    'uses' => 'ProductcategoryController@edit',
    'as' => 'productcategory.edit'
]);
Route::get('/product-category/{id}/delete', [
    'uses' => 'ProductcategoryController@delete',
    'as' => 'productcategory.delete'
]);
Route::patch('/product-category/{id}/update', [
    'uses' => 'ProductcategoryController@update',
    'as' => 'productcategory.update'
]);
Route::get('/create-product', [
    'uses' => 'ProductController@index',
    'as' => 'product.index'
]);
Route::post('/store-product', [
    'uses' => 'ProductController@store',
    'as' => 'product.store'
]);
Route::get('/show-product-report', 'ProductController@show');

Route::get('/edit/{id}/product/{cat_id}', 'ProductController@edit');
Route::patch('/update-product/{id}', 'ProductController@update');
Route::get('/delete-product/{id}', 'ProductController@delete');
Route::get('/shop', 'ProductController@shop');
Route::get('/delete-cart/{id}', 'ProductController@deleteCart');
Route::get('/weight-plan/{id}', 'ProductController@weightPlan');

Route::get('/weekplan/{cat_id}/{week_id}', 'ProductController@weekPlan');

Route::get('/add_vegan_to_checkout/{id}', 'ProductController@getAddVeganToCheckout');

Route::get('add_review_order_to_checkout/{id}', 'ProductController@getReviewOrder');
Route::post('/review-order-store', 'ProductController@StoreReviewOrder');
Route::get('/review-order-store', 'ProductController@getStoreReviewOrder');
Route::get('/add-snacks-to-checkout/{id}', 'ProductController@addSnacksToCheckout');
Route::get('/add_free_snacks_to_checkout', 'ProductController@getAddFreeSnacksToCheckout');
Route::get('/add_extra_snacks_to_checkout', 'ProductController@getAddExtraSnacksToCheckout');
Route::post('/add_extra_snacks_to_checkout', 'ProductController@addExtraSnacksToCheckout');
Route::get('/redirect_to_register', 'ProductController@redirectToRegister');
// Route::post('/delivery_info', 'ProductController@storeDeliveryInfo');


Route::post('/add_to_checkout', 'ProductController@addToCheckoutanil');
Route::get('/set-meal-plan', 'FacilityController@setMealPlan');
Route::get('/meals', 'FacilityController@showmeals');
Route::get('/deleteSetMeal/{id}', 'ProductController@deleteSetMeal');


// paypal routes
Route::get('/add_to_checkout', 'ProductController@getAddToCheckout')->name('add_to_checkout');

Route::post('/custom-paypal-checkout', 'CustomPaymentController@payWithPaypal');

Route::get('/custom-paypal-checkout-status', 'CustomPaymentController@getPaymentStatus')->name('customstatus');
// ends paypal routes


Route::post('/add-to-cart/{id}', [
    'uses' => 'ProductController@getAddToCart',
    'as' => 'product.addToCart'
]);
Route::get('/shopping-cart', [
    'uses' => 'ProductController@getCart',
    'as' => 'product.shoppingcart'
]);

Route::get('/tinymce_example', function () {
    return view('mceImageUpload::example');
});
Route::get('/tiny', function () {
    return view('test');
});



Route::get('register/verify/{api_token}/{email}', [
    'as' => 'confirmation_path',
    'uses' => 'ProfileController@confirm'
]);


//for naati dictionary

/*
Auth::routes();

Route::get('/', 'ChatsController@index');
Route::get('messages', 'ChatsController@fetchMessages');
Route::post('messages', 'ChatsController@sendMessage');*/

Route::get('/terms-and-condition', function () {
    return view('T&C');
});

Route::get('/privacy-policy', function () {
    return view('privacy-policy');
});

Route::get('/faqs', function () {
    return view('faqs');
});

// Route::get('/custom-meal-plans', function(){
//     return view('customMealPlans');
// });

// Route::get('/custom-meal-plans', 'CustomPlanController@customIndex');
// Route::get('/custom-meal-plans/{weekplanid}/{id}/{userId}', 'CustomPlanController@storeCustomPlan');
Route::get('/main-meal-page/{weekplanid}/{id}/{temp_user_id}', 'CustomPlanController@getMainMealPage');
Route::post('/add_to_basket', 'CustomPlanController@addToBasket');
Route::post('/update_basket_data/{temp_id}/{meal}/{vegcarb}/{sn}', 'CustomPlanController@updateBasketData');
Route::get('/read-data/{temp}', 'CustomPlanController@readData');
Route::get('/redirect-to-register/{id}', 'CustomPlanController@redirectToRegister');
Route::get('/redirect-from-custom/{week_id}/{id}', 'CustomPlanController@redirectFromCustom');
Route::get('/redirect-from-custom-to-register', 'CustomPlanController@redirectFromCustomToRegister');
// Route::get('/custom-edit/{userId}/{planNo}', 'CustomPlanController@customEdit');
// Route::get('/custom-edit-email/{order_id}/{plan_no}', 'CustomPlanController@customEditEmail');
// Route::post('/custom-delete/{userId}/{planNo}', 'CustomPlanController@customDelete');
Route::get('/set-delete/{id}', 'CustomPlanController@setDelete');
Route::post('/update_edit_basket_data/{user_id}/{planNo}/{meal}/{vegcarb}/{sn}', 'CustomPlanController@updateEditBasketData');
Route::get('/read-edit-data/{userId}/{planNo}', 'CustomPlanController@readEditData');
Route::post('/add_to_edit_basket', 'CustomPlanController@addToEditBasket');


Route::get('/menu/{id}', 'MenuUploaderController@pdf');



Route::group(['middleware' => ['auth', 'admin']], function () {

    Route::get('/show-custom-plan', 'AdminCustomController@index');
    Route::get('/create-custom-plan', 'AdminCustomController@create');
    Route::post('/store-custom-plan', 'AdminCustomController@store');
    Route::get('/show-custom-plan/{id}', 'AdminCustomController@show');
    Route::get('/edit-custom-plan/{id}', 'AdminCustomController@edit');
    Route::post('/update-custom-plan/{id}', 'AdminCustomController@update');
    Route::post('/delete-custom-plan/{id}', 'AdminCustomController@delete');

    Route::get('/show-week-plan', 'WeekPlanController@index');
    Route::get('/create-week-plan', 'WeekPlanController@create');
    Route::post('/store-week-plan', 'WeekPlanController@store');
    Route::get('/show-week-plan/{id}', 'WeekPlanController@show');
    Route::get('/edit-week-plan/{id}', 'WeekPlanController@edit');
    Route::post('/update-week-plan/{id}', 'WeekPlanController@update');
    Route::post('/delete-week-plan/{id}', 'WeekPlanController@delete');

    Route::get('/show-meal-plan', 'MealPlanController@index');
    Route::get('/create-meal-plan', 'MealPlanController@create');
    Route::post('/store-meal-plan', 'MealPlanController@store');
    Route::get('/show-meal-plan/{id}', 'MealPlanController@show');
    Route::get('/edit-meal-plan/{id}', 'MealPlanController@edit');
    Route::post('/update-meal-plan/{id}', 'MealPlanController@update');
    Route::post('/delete-meal-plan/{id}', 'MealPlanController@delete');

    Route::resource('menu_uploader', 'MenuUploaderController');

    Route::resource('coupon', 'CouponController');
});
Route::post('/applyCoupon', 'CouponController@applyCoupon');

app/Coupon.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    protected $fillable = [
    	'type', 'code', 'value', 'applied_amt', 'time_of_use', 'used_times', 'status', 'email'
    ];
}

app/Http/Controllers/CouponController.php
<?php

namespace App\Http\Controllers;

use App\Coupon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CouponController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coupons = Coupon::all();
        return view('admin-panel.coupon.index', compact('coupons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin-panel.coupon.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Coupon::create($request->all());
        return redirect('/coupon');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Coupon  $coupon
     * @return \Illuminate\Http\Response
     */
    public function show(Coupon $coupon)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Coupon  $coupon
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $coupon = Coupon::findOrFail($id);
        return view('admin-panel.coupon.edit', compact('coupon'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Coupon  $coupon
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Coupon::findOrFail($id)->update($request->all());
        return redirect('/coupon');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Coupon  $coupon
     * @return \Illuminate\Http\Response
     */
    public function destroy(Coupon $coupon)
    {

        $coupon = Coupon::where('id',$coupon->id)->delete();
        return redirect('/coupon')->with("success", 'Your Coupon Has Been Deleted.');

    }

    public function applyCoupon(Request $request){
        $coupons = Coupon::all();
        foreach($coupons as $coupon){
            if($coupon->code == $request->coupon){
                if($coupon->used_times < $coupon->time_of_use){
                    if($coupon->status == 1){
                        // $coupon->update([
                        //     'used_times' => $coupon->used_times + 1
                        // ]);
                        session()->put('coupon', $coupon->value);
                        session()->put('coupon_type', $coupon->type);
                        session()->put('coupon_code', $coupon->code);

                        return response()->json(['status' => 1, 'message' => 'Coupon has been successfully applied!']);
                    }
                    return response()->json(['status' => 2, 'message' => 'Inactive Coupon has been used.']);
                }
                return response()->json(['status' => 3, 'message' => 'Coupon has been expired!']);
            }
        }
        return response()->json(['status' => 4, 'message' => 'Coupon is Invalid.']);
    }
}

resources/views/admin-panel/coupon/create.blade.php
@extends('layouts.app')

@section('styles')
<style>
button#couponValue {
    background-color: white !important;
    border: 1px solid #c6c5c5;
}
</style>
@endsection

@section('content')
<div class="row">
    <div class="col-sm-12">
        @include('layouts.error_message')
        @include('layouts.sucess_message')
    </div>
</div>
<div class="create-post-form container-fluid">
    <div class="row">
        <div class="col-sm-3">
            @include('admin-panel.left-nav')
        </div>
        <div class="col-sm-9 ">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>ADD NEW COUPON</h4>
                </div>

                <div class="panel-body">
                    <form action="{{ route('coupon.store') }}" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="form-group">
                                <label for="type" class="col-md-4">Coupon Type</label>
                                <div class="col-md-6">
                                    <select name="type" class="form-control" id="type" onchange="setType(event)">
                                        <option value="">Select the Coupon Type</option>
                                        <option value="0">Flat Discount</option>
                                        <option value="1">Percentage Discount</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="code" class="col-md-4">Code</label>
                                <div class="col-md-4">
                                    <input type="text" name="code" class="form-control" id="couponCode" required>
                                </div>
                                <div class="col-md-2">
                                    <button class="btn btn-primary no-m" onclick="generateCode(event)">Generate
                                        Code</button>
                                </div>
                                <script>
                                function generateCode(evt) {
                                    evt.preventDefault();
                                    var result = '';
                                    var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
                                    var charactersLength = characters.length;
                                    for (var i = 0; i < 6; i++) {
                                        result += characters.charAt(Math.floor(Math.random() * charactersLength));
                                    }
                                    result = 'RRG-' + result;
                                    document.getElementById('couponCode').value = result;
                                }

                                function setType(evt) {
                                    if (evt.target.value == 1) {
                                        document.getElementById('couponValue').innerHTML = 'Percentage';
                                    } else {
                                        document.getElementById('couponValue').innerHTML = 'Amount';
                                    }
                                }
                                </script>
                            </div>
                            <div class="form-group">
                                <label for="value" class="col-md-4">Coupon Value</label>
                                <div class="col-md-4">
                                    <input type="text" name="value" class="form-control" required>
                                </div>
                                <div class="col-md-2">
                                    <button class="btn no-m btn-differ" id="couponValue" disabled>
                                        Amount
                                    </button>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="time_of_use" class="col-md-4">Time of Use</label>
                                <div class="col-md-6">
                                    <input type="text" name="time_of_use" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="status" class="col-md-4">Status</label>
                                <div class="col-md-6">
                                    <select name="status" class="form-control" required>
                                        <option value="">Select the Status</option>
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email" class="col-md-4">Promoter's Email</label>
                                <div class="col-md-6">
                                    <input type="email" name="email" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin-panel/coupon/edit.blade.php
@extends('layouts.app')

@section('styles')
<style>
button.btn.btn-primary.no-m {
    margin-top: 0px;
}

button#couponValue {
    background-color: white !important;
    border: 1px solid #c6c5c5;
}
</style>
@endsection

@section('content')
<div class="row">
    <div class="col-sm-12">
        @include('layouts.error_message')
        @include('layouts.sucess_message')
    </div>
</div>
<div class="create-post-form container-fluid">
    <div class="row">
        <div class="col-sm-3">
            @include('admin-panel.left-nav')
        </div>
        <div class="col-sm-9 ">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>UPDATE EXISTING COUPON</h4>
                </div>

                <div class="panel-body">
                    <form action="{{ route('coupon.update', $coupon->id) }}" method="POST"
                        enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="row">
                            <div class="form-group">
                                <label for="type" class="col-md-4">Coupon Type</label>
                                <div class="col-md-6">
                                    <select name="type" class="form-control" id="type" onchange="setType(event)">
                                        @if($coupon->type == 0)
                                        <option value="0">Flat Discount</option>
                                        <option value="1">Percentage Discount</option>
                                        @else
                                        <option value="1">Percentage Discount</option>
                                        <option value="0">Flat Discount</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="code" class="col-md-4">Code</label>
                                <div class="col-md-4">
                                    <input type="text" name="code" class="form-control" id="couponCode"
                                        value="{{ $coupon->code }}" required>
                                </div>
                                <div class="col-md-2">
                                    <button class="btn btn-primary no-m" onclick="generateCode(event)">Generate
                                        Code</button>
                                </div>
                                <script>
                                function generateCode(evt) {
                                    evt.preventDefault();
                                    var result = '';
                                    var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
                                    var charactersLength = characters.length;
                                    for (var i = 0; i < 6; i++) {
                                        result += characters.charAt(Math.floor(Math.random() * charactersLength));
                                    }
                                    result = 'RRG-' + result;
                                    document.getElementById('couponCode').value = result;
                                }

                                function setType(evt) {
                                    if (evt.target.value == 1) {
                                        document.getElementById('couponValue').innerHTML = 'Percentage';
                                    } else {
                                        document.getElementById('couponValue').innerHTML = 'Amount';
                                    }
                                }
                                </script>
                            </div>
                            <div class="form-group">
                                <label for="value" class="col-md-4">Coupon Value</label>
                                <div class="col-md-4">
                                    <input type="text" name="value" class="form-control" value="{{ $coupon->value }}"
                                        required>
                                </div>
                                <div class="col-md-2">
                                    <button class="btn no-m btn-differ" id="couponValue" disabled>
                                        Amount
                                    </button>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="time_of_use" class="col-md-4">Time of Use</label>
                                <div class="col-md-6">
                                    <input type="text" name="time_of_use" class="form-control"
                                        value="{{ $coupon->time_of_use }}" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="status" class="col-md-4">Status</label>
                                <div class="col-md-6">
                                    <select name="status" class="form-control" required>
                                        @if($coupon->status == 1)
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                        @else
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email" class="col-md-4">Promoter's Email</label>
                                <div class="col-md-6">
                                    <input type="email" name="email" class="form-control" value="{{ $coupon->email }}"
                                        required>
                                </div>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin-panel/coupon/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-12">
        @include('layouts.error_message')
        @include('layouts.sucess_message')
    </div>
</div>
<div class="create-post-form">

    <div class="row">
        <div class="col-sm-3">
            @include('admin-panel.left-nav')
        </div>
        <div class="col-sm-9 ">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>COUPONS</h4>
                </div>

                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <th>S.N</th>
                            <th>Type</th>
                            <th>Code</th>
                            <th>Coupon Value</th>
                            <th>Time Of Use</th>
                            <th>Used Times</th>
                            <th>Promoter's Email</th>
                            <th>Status</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            @foreach($coupons as $coupon)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    @if($coupon->type == 0)
                                    {{ 'Flat Discount' }}
                                    @else
                                    {{ 'Percentage Discount' }}
                                    @endif
                                </td>
                                <td>{{ $coupon->code }}</td>
                                <td>
                                    @if($coupon->type == 0)
                                    {{ '£ ' . $coupon->value }}
                                    @else
                                    {{ $coupon->value . ' %' }}
                                    @endif
                                </td>
                                <td>
                                    {{ $coupon->time_of_use }}
                                </td>
                                <td>
                                    @if($coupon->used_times)
                                    {{ $coupon->used_times }}
                                    @else
                                    {{ '0' }}
                                    @endif
                                </td>
                                <td>
                                    {{ $coupon->email }}
                                </td>
                                <td>
                                    @if($coupon->status == 0)
                                    {{ 'Inactive' }}
                                    @else
                                    {{ 'Active' }}
                                    @endif
                                </td>
                                <td>
                                    <a href="{{ route('coupon.edit', $coupon->id) }}" class="btn btn-block">Edit</a>
                                    <form action="{{ route('coupon.destroy', $coupon->id) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button class="btn btn-danger btn-block"
                                            style="background: #d9534f !important; margin-top: 7px;"
                                            onclick="alertPromt(event)">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function alertPromt(evt) {
    var result = confirm('Are you sure to delete?');
    if (!sssresult) {
        evt.stopPropagation();
        evt.preventDefault();
    }
}
</script>
@endsection